---
- name: reboot system
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for boot to complete
  local_action: >
    wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }}
      delay=120 search_regex=OpenSSH
  become: no
